    onAbort="" 
    onBlur="" 
    onClick="" 
    onChange="" 
    onError="" 
    onFocus=""
    onLoad=""
    onMouseOut=""
    onMouseOver=""
    onReset=""
    onSelect=""
    onSubmit=""
    onUnload=""
    onDblClick=""
    onDragDrop=""
    onKeyDown=""
    onKeyPress=""
    onMouseDown=""
    OnMouseMove=""
    onMove=""
    onResize="" 
    
    onAbort="console.debug('abort');" 
    onBlur="console.debug('blur');" 
    onClick="console.debug('click');" 
    onChange="console.debug('change');" 
    onError="console.debug('error');" 
    onFocus="console.debug('focus');"
    onLoad="console.debug('load');"
    onMouseOut="console.debug('mouseout');"
    onMouseOver="console.debug('mouseover');"
    onReset="console.debug('reset');"
    onSelect="console.debug('select');"
    onSubmit="console.debug('submit');"
    onUnload="console.debug('unload');"
    onDblClick="console.debug('dblclick');"
    onDragDrop="console.debug('dragdrop');"
    onKeyDown="console.debug('keydown');"
    onKeyPress="console.debug('keypress');"
    onMouseDown="console.debug('mousedown');"
    OnMouseMove="console.debug('mosemove');"
    onMove="console.debug('move');"
    onResize="console.debug('resize');"
    
onafterupdate="" Se dispara despues de la transferencia de datos entre el objeto y el proveedor de datos
onbeforeupdate="" Se dispara antes de la transferencia de datos entre el objeto y el proveedor de datos
onerrorupdate="" Se dispara cuando el manejador de eventos onbeforeupdate especificado en el objeto ha cancelado la transferencia de datos y se dispara en lugar de onafterupdate
onblur="" Se dispara cuando el objeto pierde el foco de entrada
onchange="" cuando el contenido de un objeto o selección ha cambiado
onclick="" Cuando el usuario pulsa el botón izquierdo del ratón sobre el objeto
ondblclick="" Cuando el usuario realiza una pulsación doble en el objeto
ondrag="" Se dispara continuamente en el objeto fuente durante una operación de arrastre.
ondragend="" Se dispara en el objeto fuente al finalizar una opreación de arrastre.
ondragenter="" Se dispara en el elemento de destino cuando el objeto arrastrado se introduce en un elemento válido para ser soltado.
ondragstart="" Se dispara en el objeto fuente cuando el usuario comienza a arrastrar un texto u objeto seleccionado.
ondrop="" Se dispara en el objeto destino cuando se suelta el botón del ratón durante una opreación de arrastre.
onfilterchange="" Se dispara cuando un filtro visual cambia su estado o completa una transición
onfocus="" Se dispara cuando el objeto recibe el foco.
onhelp="" Se dispara cuando el usuario pulsa la tecla F1 mientras la ventana actual es el navegador.
onkeydown="" Se dispara cuando el usuario realiza la bajada correspondiente a una pulsación de una tecla.
onkeypress="" Se dispara cuando el usuario pulsa una tecla.
onkeyup="" Se dispara cuando el usuario realiza la subida corrspondiente a una pulsación de tecla.
onlosecapture="" se dispara cuando el objeto pierde la captura del ratón.
onmousedown ="" se dispara cuando el usuario pulsa sobre el objeto con cualquier botón.
onmousemove ="" Se dispara cuando el usuario mueve el ratón sobre el objeto.
onmouseout="" Se dispara cuando el usuario mueve el puntero del ratón desde dentro hacia fuera del objeto.
onmouseover="" Se dispara cuando el usuario mueve el puntero del ratón desde fuera hacia dentro del objeto.
onmouseup="" Se dispara cuando el usuario suelta un botón del ratón situado sobre el objeto.
onpropertychange="" Se dispara cuando una propiedad cambia en el objeto.
onresize="" Se dispara cuando se cambia el tamaño de un objeto.
onselectstart="" Se dispara cuando el objeto está siendo seleccionado.


onafterupdate="console.debug('onafterupdate');" 
onbeforeupdate="console.debug('onbeforeupdate');"
onerrorupdate="console.debug('onerrorupdate');" 
onblur="console.debug('onblur');"
onchange="console.debug('onchange');"
onclick="console.debug('onclick');"
ondblclick="console.debug('ondblclick');"
ondrag="console.debug('ondrag');"
ondragend="console.debug('ondragend');"
ondragenter="console.debug('ondragenter');"
ondragstart="console.debug('ondragstart');"
ondrop="console.debug('ondrop');"
onfilterchange="console.debug('');"
onfocus="console.debug('onfocus');"
onhelp="console.debug('onhelp');"
onkeydown="console.debug('onkeydown');"
onkeypress="console.debug('onkeypress');"
onkeyup="console.debug('onkeyup');"
onlosecapture="console.debug('onlosecapture');"
onmousedown ="console.debug('onmousedown');"
onmousemove ="console.debug('onmousemove');"
onmouseout="console.debug('onmouseout');"
onmouseover="console.debug('onmouseover');"
onmouseup="console.debug('onmouseup');"
onpropertychange="console.debug('onpropertychange');"
onresize="console.debug('onresize');"
onselectstart="console.debug('onselectstart');"