--sp_help 'tabla'

-- RELACION DE TABLA (DEPENDENCIAS)
SELECT
    FK_Table = FK.TABLE_NAME
    ,FK_Column = CU.COLUMN_NAME
    ,PK_Table = PK.TABLE_NAME
    ,PK_Column = PT.COLUMN_NAME
    ,ConstraintName = C.CONSTRAINT_NAME
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS C
INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS FK
ON C.CONSTRAINT_NAME = FK.CONSTRAINT_NAME
INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS PK
ON C.UNIQUE_CONSTRAINT_NAME = PK.CONSTRAINT_NAME
INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE CU
ON C.CONSTRAINT_NAME = CU.CONSTRAINT_NAME
INNER JOIN
(
    SELECT
    TC.TABLE_NAME
    ,CU.COLUMN_NAME
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC
    INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE CU
    ON TC.CONSTRAINT_NAME = CU.CONSTRAINT_NAME
    WHERE TC.CONSTRAINT_TYPE = 'PRIMARY KEY'
) PT
ON PT.TABLE_NAME = PK.TABLE_NAME
WHERE 1=1
AND PK.TABLE_NAME = 'products' -- TU TABLA